server:
  port: 10001
  
logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework: DEBUG  

learning-spring-cloud-microservice-provider:
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList  #从eureka服务器上面获取learning-spring-cloud-microservice-provider的实例 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.NoOpPing
    
spring:
  application:
    name: learning-spring-cloud-microservice-consumer

eureka:
  client:
    register-with-eureka: true
    healthcheck: 
      enable: true # 对应的类名：EurekaDiscoveryClientConfiguration.class
    serviceUrl:
      defaultZone: http://admin:admin@peer1:3001/eureka
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  
  
  