server:
  port: 10001
  
logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework: DEBUG
      
#learning-spring-cloud-microservice-provider:
#  ribbon:
#    listOfServers: localhost:9001,localhost:9002
    
spring:
  application:
    name: learning-spring-cloud-microservice-consumer

  